services:
  - type: web
    name: server
    runtime: node
    plan: free
    buildCommand: |
      cd client && npm install && npm run build
      cd ../server && npm install
    startCommand: node server.js
    rootDir: server